# Generated by Django 5.2.12 on 2026-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('csr', 'CSR'), ('loan_officer', 'Loan Officer'), ('branch_manager', 'Branch Manager'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
