# Generated by Django 5.2.12 on 2026-04-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AddField(
            model_name='loan',
            name='username',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
