# Generated by Django 5.2.12 on 2026-04-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_loan_user_loan_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='officer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
