# Generated by Django 5.2.12 on 2026-04-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loan_officer_approved_alter_loan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='officer_approved',
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='Pending Verification', max_length=50),
        ),
    ]
