# Generated by Django 5.2.12 on 2026-04-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_loan_officer_approved_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='officer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='Pending Verification', max_length=30),
        ),
    ]
