# Generated by Django 5.2.13 on 2026-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loan_officer_approved_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
