# Generated by Django 5.2.13 on 2026-04-25 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_loan_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
