# Generated by Django 5.2.13 on 2026-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_is_approved_remove_loan_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
