# Generated by Django 5.2.13 on 2026-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_loan_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
